"""Provided by the supervisor for P0-I1-T06. Make these pass; do not edit this file."""

from __future__ import annotations

import threading
from collections.abc import Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from sqlalchemy import Engine, text
from sqlalchemy.exc import IntegrityError
from tl_adapters.sqlite.engine import make_engine, write_tx
from tl_adapters.sqlite.ledger import SqliteLedger
from tl_core.ledger import ConcurrencyError, NewEvent, canonical_json, event_hash, iso_utc

BASE_TIME = datetime(2026, 1, 1, tzinfo=UTC)


class FakeClock:
    """Each call returns the next second after BASE_TIME."""

    def __init__(self) -> None:
        self.calls = 0

    def __call__(self) -> datetime:
        self.calls += 1
        return BASE_TIME + timedelta(seconds=self.calls)


class FakeIds:
    """Sequential 26-character ids: E0000000000000000000000001, ..."""

    def __init__(self) -> None:
        self.calls = 0

    def __call__(self) -> str:
        self.calls += 1
        return f"E{self.calls:025d}"


@pytest.fixture
def engine(tmp_path: Path) -> Iterator[Engine]:
    eng = make_engine(tmp_path / "ledger.db")
    yield eng
    eng.dispose()


@pytest.fixture
def ledger(engine: Engine) -> SqliteLedger:
    led = SqliteLedger(engine, clock=FakeClock(), id_gen=FakeIds())
    led.create_schema()
    return led


def ev(name: str = "Record.Created", **payload: object) -> NewEvent:
    return NewEvent(event_type=name, payload=dict(payload) or {"n": 1})


def append(
    ledger: SqliteLedger,
    stream: str,
    expected: int,
    events: list[NewEvent],
    scope: str = "project:P1",
):
    return ledger.append(
        stream_id=stream,
        stream_type="core.Record",
        scope=scope,
        expected_version=expected,
        events=events,
        actor="user:dev",
        source="test",
        correlation_id="corr-1",
    )


def test_new_stream_append_fills_ledger_fields(ledger: SqliteLedger) -> None:
    result = append(ledger, "s1", 0, [ev(title="First")])
    assert result.new_version == 1
    assert result.last_seq == 1
    (event,) = result.events
    assert (event.seq, event.stream_version, event.stream_id) == (1, 1, "s1")
    assert event.event_id == "E0000000000000000000000001"
    assert event.recorded_at == BASE_TIME + timedelta(seconds=1)
    assert event.effective_at == event.recorded_at
    assert event.prev_hash is None
    assert len(event.hash) == 64
    assert event.payload == {"title": "First"}
    assert (event.actor, event.source, event.correlation_id) == ("user:dev", "test", "corr-1")
    assert event.causation_id is None
    assert ledger.read_stream("s1") == [event]


def test_explicit_effective_at_is_kept(ledger: SqliteLedger) -> None:
    when = datetime(2025, 12, 25, 8, 30, tzinfo=UTC)
    result = append(
        ledger, "s1", 0, [NewEvent(event_type="Record.Created", payload={}, effective_at=when)]
    )
    assert result.events[0].effective_at == when
    assert ledger.read_stream("s1")[0].effective_at == when


def test_version_increments_across_appends(ledger: SqliteLedger) -> None:
    append(ledger, "s1", 0, [ev()])
    second = append(ledger, "s1", 1, [ev("Record.Updated"), ev("Record.Updated")])
    assert second.new_version == 3
    assert [e.stream_version for e in second.events] == [2, 3]
    assert ledger.stream_version("s1") == 3
    assert [e.event_type for e in ledger.read_stream("s1")] == [
        "Record.Created",
        "Record.Updated",
        "Record.Updated",
    ]


def test_stale_expected_version_raises_and_writes_nothing(ledger: SqliteLedger) -> None:
    append(ledger, "s1", 0, [ev()])
    with pytest.raises(ConcurrencyError):
        append(ledger, "s1", 0, [ev("Record.Updated")])
    with pytest.raises(ConcurrencyError):
        append(ledger, "s1", 5, [ev("Record.Updated")])
    assert ledger.stream_version("s1") == 1
    assert ledger.head_seq() == 1


def test_empty_batch_is_rejected(ledger: SqliteLedger) -> None:
    with pytest.raises(ValueError):
        append(ledger, "s1", 0, [])


def test_hash_chain_is_per_scope(ledger: SqliteLedger) -> None:
    a1 = append(ledger, "a", 0, [ev()], scope="project:A").events[0]
    b1 = append(ledger, "b", 0, [ev()], scope="project:B").events[0]
    a2 = append(ledger, "a", 1, [ev("Record.Updated")], scope="project:A").events[0]
    b2 = append(ledger, "b", 1, [ev("Record.Updated")], scope="project:B").events[0]
    assert a1.prev_hash is None and b1.prev_hash is None
    assert a2.prev_hash == a1.hash
    assert b2.prev_hash == b1.hash
    assert a2.prev_hash != b1.hash


def test_batch_of_three_chains_internally(ledger: SqliteLedger) -> None:
    result = append(
        ledger, "s1", 0, [ev(i=1), ev("Record.Updated", i=2), ev("Record.Updated", i=3)]
    )
    first, second, third = result.events
    assert first.prev_hash is None
    assert second.prev_hash == first.hash
    assert third.prev_hash == second.hash
    assert [e.seq for e in result.events] == [1, 2, 3]
    assert result.last_seq == 3


def test_stored_hash_can_be_recomputed(ledger: SqliteLedger) -> None:
    append(ledger, "s1", 0, [ev(title="é")])
    event = append(ledger, "s1", 1, [ev("Record.Updated", title="ü")]).events[0]
    stored = ledger.read_stream("s1")[1]
    assert stored == event
    expected = event_hash(
        stored.prev_hash,
        stored.event_id,
        stored.stream_id,
        stored.stream_version,
        stored.event_type,
        canonical_json(stored.payload),
        iso_utc(stored.recorded_at),
    )
    assert stored.hash == expected
    assert stored.payload == {"title": "ü"}


def test_read_after_orders_by_seq_and_honours_limit_and_scope(ledger: SqliteLedger) -> None:
    append(ledger, "a", 0, [ev()], scope="project:A")
    append(ledger, "b", 0, [ev()], scope="project:B")
    append(ledger, "a", 1, [ev("Record.Updated")], scope="project:A")
    append(ledger, "c", 0, [ev()], scope="company")
    assert [e.seq for e in ledger.read_after(0)] == [1, 2, 3, 4]
    assert [e.seq for e in ledger.read_after(1)] == [2, 3, 4]
    assert [e.seq for e in ledger.read_after(0, limit=2)] == [1, 2]
    assert [e.seq for e in ledger.read_after(0, scope="project:A")] == [1, 3]
    assert ledger.read_after(4) == []


def test_read_stream_from_version(ledger: SqliteLedger) -> None:
    append(ledger, "s1", 0, [ev(), ev("Record.Updated"), ev("Record.Updated")])
    assert [e.stream_version for e in ledger.read_stream("s1")] == [1, 2, 3]
    assert [e.stream_version for e in ledger.read_stream("s1", from_version=2)] == [2, 3]
    assert ledger.read_stream("missing") == []


def test_empty_ledger_head_and_versions(ledger: SqliteLedger) -> None:
    assert ledger.head_seq() == 0
    assert ledger.stream_version("nope") == 0


def test_update_and_delete_are_rejected(ledger: SqliteLedger, engine: Engine) -> None:
    append(ledger, "s1", 0, [ev()])
    with pytest.raises(IntegrityError, match="append-only"), engine.begin() as conn:
        conn.execute(text("UPDATE events SET actor = 'user:evil'"))
    with pytest.raises(IntegrityError, match="append-only"), engine.begin() as conn:
        conn.execute(text("DELETE FROM events"))
    assert ledger.read_stream("s1")[0].actor == "user:dev"


def test_create_schema_is_idempotent(ledger: SqliteLedger) -> None:
    append(ledger, "s1", 0, [ev()])
    ledger.create_schema()
    assert ledger.head_seq() == 1


def test_append_in_shares_the_callers_transaction(ledger: SqliteLedger, engine: Engine) -> None:
    class Boom(Exception):
        pass

    with pytest.raises(Boom), write_tx(engine) as conn:
        ledger.append_in(
            conn,
            stream_id="s1",
            stream_type="core.Record",
            scope="project:P1",
            expected_version=0,
            events=[ev()],
            actor="user:dev",
            source="test",
            correlation_id="c",
        )
        raise Boom
    assert ledger.head_seq() == 0
    with write_tx(engine) as conn:
        result = ledger.append_in(
            conn,
            stream_id="s1",
            stream_type="core.Record",
            scope="project:P1",
            expected_version=0,
            events=[ev(), ev("Record.Updated")],
            actor="user:dev",
            source="test",
            correlation_id="c",
        )
    assert result.new_version == 2
    assert ledger.head_seq() == 2


def test_append_in_rejects_a_read_connection(ledger: SqliteLedger, engine: Engine) -> None:
    with engine.connect() as conn, pytest.raises(RuntimeError, match="write_tx"):
        ledger.append_in(
            conn,
            stream_id="s1",
            stream_type="core.Record",
            scope="project:P1",
            expected_version=0,
            events=[ev()],
            actor="user:dev",
            source="test",
            correlation_id="c",
        )


def test_concurrent_writers_on_one_stream_exactly_one_wins(tmp_path: Path) -> None:
    eng = make_engine(tmp_path / "race.db")
    SqliteLedger(eng).create_schema()
    outcomes: list[str] = []
    barrier = threading.Barrier(2)

    def worker() -> None:
        led = SqliteLedger(eng)
        barrier.wait()
        try:
            led.append(
                stream_id="s1",
                stream_type="core.Record",
                scope="project:P1",
                expected_version=0,
                events=[ev()],
                actor="user:dev",
                source="test",
                correlation_id="c",
            )
            outcomes.append("ok")
        except ConcurrencyError:
            outcomes.append("conflict")

    threads = [threading.Thread(target=worker) for _ in range(2)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert sorted(outcomes) == ["conflict", "ok"]
    assert SqliteLedger(eng).stream_version("s1") == 1
    eng.dispose()
